version: '3'

services:

  nginx:
    image: nginx:latest
    container_name: raspberry-pi-server_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker-webserver/nginx-conf:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    depends_on:
      - php
      - mariadb

  php:
    container_name: raspberry-pi-server_php
    build:
      dockerfile: Dockerfile
      context: ./docker-webserver
    volumes:
      - ./src:/usr/share/nginx/html
    depends_on:
      - mariadb

  mariadb:
    container_name: raspberry-pi-server_db
    image: mariadb:10.9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: raspberry-pi-serverdb
    volumes:
      - './mysqldata:/var/lib/mysql'

  adminer:
    container_name: raspberry-pi-server_adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

  ftp:
    build:
      context: ./docker-ftp-server
      dockerfile: Dockerfile
    container_name: raspberry-pi-server_ftp
    environment:
      - USERS=user1|password1|/ftp/user1|10001 user2|password2|/ftp/user2|10002 public|adminPW|/ftp/public|10003
      - ADDRESS=192.168.178.41 #needs to be changed to the static server ip
    restart: always
    ports:
      - "21:21"
      - "21000-21010:21000-21010" #passive ports
    volumes:
      - ./ftp:/ftp

volumes:
  src:
  ftp:
  mysqldata:
