version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: my_nginx
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html

  ftp:
    build:
      context: ./docker-ftp-server
      dockerfile: Dockerfile
    restart: always
    environment:
      - USERS=user1|password1|/ftp/user1|10001 user2|password2|/ftp/user2|10002 public|adminPW|/ftp/public|10003
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ./ftp-data/user1:/ftp/user1
      - ./ftp-data/user2:/ftp/user2
      - ./ftp-data/public:/ftp/public